// Generated by scripts/extract-themes.mts from the shadcn registry theme
// data (oklch values). Keys are css var names without the leading "--".
export const BASE_COLOR_VARS: Record<
  string,
  { light: Record<string, string>; dark: Record<string, string> }
> = {
  "neutral": {
    "light": {
      "background": "oklch(1 0 0)",
      "foreground": "oklch(0.145 0 0)",
      "card": "oklch(1 0 0)",
      "card-foreground": "oklch(0.145 0 0)",
      "popover": "oklch(1 0 0)",
      "popover-foreground": "oklch(0.145 0 0)",
      "primary": "oklch(0.205 0 0)",
      "primary-foreground": "oklch(0.985 0 0)",
      "secondary": "oklch(0.97 0 0)",
      "secondary-foreground": "oklch(0.205 0 0)",
      "muted": "oklch(0.97 0 0)",
      "muted-foreground": "oklch(0.556 0 0)",
      "accent": "oklch(0.97 0 0)",
      "accent-foreground": "oklch(0.205 0 0)",
      "border": "oklch(0.922 0 0)",
      "input": "oklch(0.922 0 0)",
      "ring": "oklch(0.708 0 0)"
    },
    "dark": {
      "background": "oklch(0.145 0 0)",
      "foreground": "oklch(0.985 0 0)",
      "card": "oklch(0.205 0 0)",
      "card-foreground": "oklch(0.985 0 0)",
      "popover": "oklch(0.205 0 0)",
      "popover-foreground": "oklch(0.985 0 0)",
      "primary": "oklch(0.922 0 0)",
      "primary-foreground": "oklch(0.205 0 0)",
      "secondary": "oklch(0.269 0 0)",
      "secondary-foreground": "oklch(0.985 0 0)",
      "muted": "oklch(0.269 0 0)",
      "muted-foreground": "oklch(0.708 0 0)",
      "accent": "oklch(0.269 0 0)",
      "accent-foreground": "oklch(0.985 0 0)",
      "border": "oklch(1 0 0 / 10%)",
      "input": "oklch(1 0 0 / 15%)",
      "ring": "oklch(0.556 0 0)"
    }
  },
  "stone": {
    "light": {
      "background": "oklch(1 0 0)",
      "foreground": "oklch(0.147 0.004 49.25)",
      "card": "oklch(1 0 0)",
      "card-foreground": "oklch(0.147 0.004 49.25)",
      "popover": "oklch(1 0 0)",
      "popover-foreground": "oklch(0.147 0.004 49.25)",
      "primary": "oklch(0.216 0.006 56.043)",
      "primary-foreground": "oklch(0.985 0.001 106.423)",
      "secondary": "oklch(0.97 0.001 106.424)",
      "secondary-foreground": "oklch(0.216 0.006 56.043)",
      "muted": "oklch(0.97 0.001 106.424)",
      "muted-foreground": "oklch(0.553 0.013 58.071)",
      "accent": "oklch(0.97 0.001 106.424)",
      "accent-foreground": "oklch(0.216 0.006 56.043)",
      "border": "oklch(0.923 0.003 48.717)",
      "input": "oklch(0.923 0.003 48.717)",
      "ring": "oklch(0.709 0.01 56.259)"
    },
    "dark": {
      "background": "oklch(0.147 0.004 49.25)",
      "foreground": "oklch(0.985 0.001 106.423)",
      "card": "oklch(0.216 0.006 56.043)",
      "card-foreground": "oklch(0.985 0.001 106.423)",
      "popover": "oklch(0.216 0.006 56.043)",
      "popover-foreground": "oklch(0.985 0.001 106.423)",
      "primary": "oklch(0.923 0.003 48.717)",
      "primary-foreground": "oklch(0.216 0.006 56.043)",
      "secondary": "oklch(0.268 0.007 34.298)",
      "secondary-foreground": "oklch(0.985 0.001 106.423)",
      "muted": "oklch(0.268 0.007 34.298)",
      "muted-foreground": "oklch(0.709 0.01 56.259)",
      "accent": "oklch(0.268 0.007 34.298)",
      "accent-foreground": "oklch(0.985 0.001 106.423)",
      "border": "oklch(1 0 0 / 10%)",
      "input": "oklch(1 0 0 / 15%)",
      "ring": "oklch(0.553 0.013 58.071)"
    }
  },
  "zinc": {
    "light": {
      "background": "oklch(1 0 0)",
      "foreground": "oklch(0.141 0.005 285.823)",
      "card": "oklch(1 0 0)",
      "card-foreground": "oklch(0.141 0.005 285.823)",
      "popover": "oklch(1 0 0)",
      "popover-foreground": "oklch(0.141 0.005 285.823)",
      "primary": "oklch(0.21 0.006 285.885)",
      "primary-foreground": "oklch(0.985 0 0)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)",
      "muted": "oklch(0.967 0.001 286.375)",
      "muted-foreground": "oklch(0.552 0.016 285.938)",
      "accent": "oklch(0.967 0.001 286.375)",
      "accent-foreground": "oklch(0.21 0.006 285.885)",
      "border": "oklch(0.92 0.004 286.32)",
      "input": "oklch(0.92 0.004 286.32)",
      "ring": "oklch(0.705 0.015 286.067)"
    },
    "dark": {
      "background": "oklch(0.141 0.005 285.823)",
      "foreground": "oklch(0.985 0 0)",
      "card": "oklch(0.21 0.006 285.885)",
      "card-foreground": "oklch(0.985 0 0)",
      "popover": "oklch(0.21 0.006 285.885)",
      "popover-foreground": "oklch(0.985 0 0)",
      "primary": "oklch(0.92 0.004 286.32)",
      "primary-foreground": "oklch(0.21 0.006 285.885)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)",
      "muted": "oklch(0.274 0.006 286.033)",
      "muted-foreground": "oklch(0.705 0.015 286.067)",
      "accent": "oklch(0.274 0.006 286.033)",
      "accent-foreground": "oklch(0.985 0 0)",
      "border": "oklch(1 0 0 / 10%)",
      "input": "oklch(1 0 0 / 15%)",
      "ring": "oklch(0.552 0.016 285.938)"
    }
  },
  "gray": {
    "light": {
      "background": "oklch(1 0 0)",
      "foreground": "oklch(0.141 0.005 285.823)",
      "card": "oklch(1 0 0)",
      "card-foreground": "oklch(0.141 0.005 285.823)",
      "popover": "oklch(1 0 0)",
      "popover-foreground": "oklch(0.141 0.005 285.823)",
      "primary": "oklch(0.21 0.006 285.885)",
      "primary-foreground": "oklch(0.985 0 0)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)",
      "muted": "oklch(0.967 0.001 286.375)",
      "muted-foreground": "oklch(0.552 0.016 285.938)",
      "accent": "oklch(0.967 0.001 286.375)",
      "accent-foreground": "oklch(0.21 0.006 285.885)",
      "border": "oklch(0.92 0.004 286.32)",
      "input": "oklch(0.92 0.004 286.32)",
      "ring": "oklch(0.705 0.015 286.067)"
    },
    "dark": {
      "background": "oklch(0.141 0.005 285.823)",
      "foreground": "oklch(0.985 0 0)",
      "card": "oklch(0.21 0.006 285.885)",
      "card-foreground": "oklch(0.985 0 0)",
      "popover": "oklch(0.21 0.006 285.885)",
      "popover-foreground": "oklch(0.985 0 0)",
      "primary": "oklch(0.92 0.004 286.32)",
      "primary-foreground": "oklch(0.21 0.006 285.885)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)",
      "muted": "oklch(0.274 0.006 286.033)",
      "muted-foreground": "oklch(0.705 0.015 286.067)",
      "accent": "oklch(0.274 0.006 286.033)",
      "accent-foreground": "oklch(0.985 0 0)",
      "border": "oklch(1 0 0 / 10%)",
      "input": "oklch(1 0 0 / 15%)",
      "ring": "oklch(0.552 0.016 285.938)"
    }
  }
}

export const THEME_VARS: Record<
  string,
  { light: Record<string, string>; dark: Record<string, string> }
> = {
  "neutral": {
    "light": {
      "primary": "oklch(0.205 0 0)",
      "primary-foreground": "oklch(0.985 0 0)",
      "secondary": "oklch(0.97 0 0)",
      "secondary-foreground": "oklch(0.205 0 0)",
      "ring": "oklch(0.708 0 0)"
    },
    "dark": {
      "primary": "oklch(0.922 0 0)",
      "primary-foreground": "oklch(0.205 0 0)",
      "secondary": "oklch(0.269 0 0)",
      "secondary-foreground": "oklch(0.985 0 0)",
      "ring": "oklch(0.556 0 0)"
    }
  },
  "amber": {
    "light": {
      "primary": "oklch(0.555 0.163 48.998)",
      "primary-foreground": "oklch(0.987 0.022 95.277)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.473 0.137 46.201)",
      "primary-foreground": "oklch(0.987 0.022 95.277)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "blue": {
    "light": {
      "primary": "oklch(0.488 0.243 264.376)",
      "primary-foreground": "oklch(0.97 0.014 254.604)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.424 0.199 265.638)",
      "primary-foreground": "oklch(0.97 0.014 254.604)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "cyan": {
    "light": {
      "primary": "oklch(0.52 0.105 223.128)",
      "primary-foreground": "oklch(0.984 0.019 200.873)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.45 0.085 224.283)",
      "primary-foreground": "oklch(0.984 0.019 200.873)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "emerald": {
    "light": {
      "primary": "oklch(0.508 0.118 165.612)",
      "primary-foreground": "oklch(0.979 0.021 166.113)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.432 0.095 166.913)",
      "primary-foreground": "oklch(0.979 0.021 166.113)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "fuchsia": {
    "light": {
      "primary": "oklch(0.518 0.253 323.949)",
      "primary-foreground": "oklch(0.977 0.017 320.058)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.452 0.211 324.591)",
      "primary-foreground": "oklch(0.977 0.017 320.058)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "green": {
    "light": {
      "primary": "oklch(0.527 0.154 150.069)",
      "primary-foreground": "oklch(0.982 0.018 155.826)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.448 0.119 151.328)",
      "primary-foreground": "oklch(0.982 0.018 155.826)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "indigo": {
    "light": {
      "primary": "oklch(0.457 0.24 277.023)",
      "primary-foreground": "oklch(0.962 0.018 272.314)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.398 0.195 277.366)",
      "primary-foreground": "oklch(0.962 0.018 272.314)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "lime": {
    "light": {
      "primary": "oklch(0.841 0.238 128.85)",
      "primary-foreground": "oklch(0.405 0.101 131.063)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.768 0.233 130.85)",
      "primary-foreground": "oklch(0.405 0.101 131.063)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "orange": {
    "light": {
      "primary": "oklch(0.553 0.195 38.402)",
      "primary-foreground": "oklch(0.98 0.016 73.684)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.47 0.157 37.304)",
      "primary-foreground": "oklch(0.98 0.016 73.684)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "pink": {
    "light": {
      "primary": "oklch(0.525 0.223 3.958)",
      "primary-foreground": "oklch(0.971 0.014 343.198)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.459 0.187 3.815)",
      "primary-foreground": "oklch(0.971 0.014 343.198)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "purple": {
    "light": {
      "primary": "oklch(0.496 0.265 301.924)",
      "primary-foreground": "oklch(0.977 0.014 308.299)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.438 0.218 303.724)",
      "primary-foreground": "oklch(0.977 0.014 308.299)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "red": {
    "light": {
      "primary": "oklch(0.505 0.213 27.518)",
      "primary-foreground": "oklch(0.971 0.013 17.38)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.444 0.177 26.899)",
      "primary-foreground": "oklch(0.971 0.013 17.38)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "rose": {
    "light": {
      "primary": "oklch(0.514 0.222 16.935)",
      "primary-foreground": "oklch(0.969 0.015 12.422)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.455 0.188 13.697)",
      "primary-foreground": "oklch(0.969 0.015 12.422)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "sky": {
    "light": {
      "primary": "oklch(0.5 0.134 242.749)",
      "primary-foreground": "oklch(0.977 0.013 236.62)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.443 0.11 240.79)",
      "primary-foreground": "oklch(0.977 0.013 236.62)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "teal": {
    "light": {
      "primary": "oklch(0.511 0.096 186.391)",
      "primary-foreground": "oklch(0.984 0.014 180.72)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.437 0.078 188.216)",
      "primary-foreground": "oklch(0.984 0.014 180.72)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "violet": {
    "light": {
      "primary": "oklch(0.491 0.27 292.581)",
      "primary-foreground": "oklch(0.969 0.016 293.756)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.432 0.232 292.759)",
      "primary-foreground": "oklch(0.969 0.016 293.756)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  },
  "yellow": {
    "light": {
      "primary": "oklch(0.852 0.199 91.936)",
      "primary-foreground": "oklch(0.421 0.095 57.708)",
      "secondary": "oklch(0.967 0.001 286.375)",
      "secondary-foreground": "oklch(0.21 0.006 285.885)"
    },
    "dark": {
      "primary": "oklch(0.795 0.184 86.047)",
      "primary-foreground": "oklch(0.421 0.095 57.708)",
      "secondary": "oklch(0.274 0.006 286.033)",
      "secondary-foreground": "oklch(0.985 0 0)"
    }
  }
}
