import fs from "node:fs"
import path from "node:path"

/**
 * Generates the preview barrels:
 *   components/previews/index.ts    - themed previews (docs catalog, sidebar)
 *   components/previews/og/index.ts - Satori-safe previews (opengraph routes)
 *
 * Scans each directory for <kebab>.tsx modules exporting a `<Name>Preview`
 * function and re-exports them. Regenerate with bun after adding a preview:
 *   bun scripts/generate-preview-map.mts
 * Wired into predev/prebuild - runs automatically.
 */

const previewsDir = path.join(process.cwd(), "components", "previews")
const ogDir = path.join(previewsDir, "og")

const scan = (dir: string) =>
  fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".tsx") && f !== "shared.tsx")
    .sort()
    .flatMap((file) => {
      const source = fs.readFileSync(path.join(dir, file), "utf8")
      return [...source.matchAll(/export (?:async )?function (\w+Preview)\b/g)].map(
        (m) => ({ name: m[1]!, file })
      )
    })

const barrel = (items: { name: string; file: string }[]) =>
  `/** GENERATED by scripts/generate-preview-map.mts - do not edit. */\n${items
    .map((i) => `export { ${i.name} } from "./${i.file.replace(/\.tsx$/, "")}"`)
    .join("\n")}\n`

// Slug -> component map consumed by app/docs/og/[...slug]/route.tsx so
// every docs page resolves its OG preview without a per-page route file.
const ogMap = (items: { name: string; file: string }[]) => {
  const slugOf = (i: { file: string }) => i.file.replace(/\.tsx$/, "")
  return `/** GENERATED by scripts/generate-preview-map.mts - do not edit. */
import type { ComponentType } from "react"
${items
  .map((i) => `import { ${i.name} } from "./${slugOf(i)}"`)
  .join("\n")}

export const OG_PREVIEWS: Record<string, ComponentType> = {
${items.map((i) => `  "${slugOf(i)}": ${i.name},`).join("\n")}
}
`
}

fs.writeFileSync(path.join(previewsDir, "index.ts"), barrel(scan(previewsDir)))
const ogItems = scan(ogDir)
fs.writeFileSync(path.join(ogDir, "index.ts"), barrel(ogItems))
fs.writeFileSync(path.join(ogDir, "__map__.ts"), ogMap(ogItems))
console.log(
  `preview barrels: ${scan(previewsDir).length} themed, ${ogItems.length} og`
)
