import fs from "node:fs"
import path from "node:path"

/**
 * Generates components/examples/__map__.ts — a name -> lazy-loader record
 * for every example file under components/examples/. Doc MDX references
 * examples by name (<ComponentPreview name="alert-demo" />) and this map
 * resolves them to live components, mirroring how the shadcn/ui docs site
 * resolves its registry demos.
 */

const examplesDir = path.join(process.cwd(), "components", "examples")
const outFile = path.join(examplesDir, "__map__.ts")

const files = fs
  .readdirSync(examplesDir)
  .filter((file) => file.endsWith(".tsx"))
  .sort()

const entries: string[] = []
const typeEntries: string[] = []

for (const file of files) {
  const source = fs.readFileSync(path.join(examplesDir, file), "utf8")
  // Components follow the "export function <Name>Example()" convention;
  // other exports (types, column defs) are not renderable examples.
  const exportNames = [...source.matchAll(/export (?:async )?function (\w+)/g)].map(
    (match) => match[1]!
  )

  if (exportNames.length === 0) {
    console.warn(`[example-map] no exports found in ${file}, skipping`)
    continue
  }

  const base = file.replace(/\.tsx$/, "")
  for (const exportName of exportNames) {
    // One export per file is the convention; extra exports still get mapped
    // so nothing silently breaks.
    const key =
      exportNames.length === 1
        ? base
        : `${base}#${exportName.toLowerCase()}`
    entries.push(
      `  "${key}": () => import("@/components/examples/${base}").then((m) => m.${exportName}),`
    )
    typeEntries.push(`  "${key}": React.ComponentType;`)
  }
}

const content = `// GENERATED by scripts/generate-example-map.mts — do not edit.
// Run \`bun scripts/generate-example-map.mts\` after adding/removing examples.
import type * as React from "react"

export const exampleLoaders: Record<string, () => Promise<React.ComponentType>> = {
${entries.join("\n")}
}

export type ExampleMap = {
${typeEntries.join("\n")}
}
`

fs.writeFileSync(outFile, content)
console.log(`[example-map] wrote ${entries.length} entries -> ${path.relative(process.cwd(), outFile)}`)
