/** GENERATED by scripts/generate-preview-map.mts - do not edit. */
import type { ComponentType } from "react"
import { AccordionPreview } from "./accordion"
import { AlertDialogPreview } from "./alert-dialog"
import { AlertPreview } from "./alert"
import { AspectRatioPreview } from "./aspect-ratio"
import { AttachmentPreview } from "./attachment"
import { AvatarPreview } from "./avatar"
import { BadgePreview } from "./badge"
import { BankInputPreview } from "./bank-input"
import { BreadcrumbPreview } from "./breadcrumb"
import { BubblePreview } from "./bubble"
import { ButtonGroupPreview } from "./button-group"
import { ButtonPreview } from "./button"
import { CalendarPreview } from "./calendar"
import { CardPreview } from "./card"
import { CarouselPreview } from "./carousel"
import { ChartsPreview } from "./charts"
import { CheckboxPreview } from "./checkbox"
import { CitySelectorPreview } from "./city-selector"
import { CollapsiblePreview } from "./collapsible"
import { ComboboxPreview } from "./combobox"
import { CommandPreview } from "./command"
import { ContextMenuPreview } from "./context-menu"
import { CopyButtonPreview } from "./copy-button"
import { DataTablePreview } from "./data-table"
import { DatePickerPreview } from "./date-picker"
import { DateWheelPickerPreview } from "./date-wheel-picker"
import { DialogPreview } from "./dialog"
import { DirectionPreview } from "./direction"
import { DrawerPreview } from "./drawer"
import { DropdownMenuPreview } from "./dropdown-menu"
import { ElasticRangeSliderPreview } from "./elastic-range-slider"
import { ElasticSliderPreview } from "./elastic-slider"
import { EmptyPreview } from "./empty"
import { FieldPreview } from "./field"
import { HitboxPreview } from "./hitbox"
import { HoverCardPreview } from "./hover-card"
import { InputGroupPreview } from "./input-group"
import { InputOTPPreview } from "./input-otp"
import { InputPreview } from "./input"
import { IranianBankPreview } from "./iranian-bank"
import { ItemPreview } from "./item"
import { KbdPreview } from "./kbd"
import { LabelPreview } from "./label"
import { MarkerPreview } from "./marker"
import { MenubarPreview } from "./menubar"
import { MessageScrollerPreview } from "./message-scroller"
import { MessagePreview } from "./message"
import { MobileNumberInputPreview } from "./mobile-number-input"
import { NationalIDInputPreview } from "./national-id-input"
import { NationalIdPreview } from "./national-id"
import { NativeSelectPreview } from "./native-select"
import { NavigationMenuPreview } from "./navigation-menu"
import { NormalizePersianDigitsPreview } from "./normalize-persian-digits"
import { NumberToPersianWordsPreview } from "./number-to-persian-words"
import { PaginationPreview } from "./pagination"
import { PasswordInputPreview } from "./password-input"
import { PersianDateZodPreview } from "./persian-date-zod"
import { PersianDatePreview } from "./persian-date"
import { PersianHolidaysPreview } from "./persian-holidays"
import { PersianReshapePreview } from "./persian-reshape"
import { PersianSlugPreview } from "./persian-slug"
import { PlateInputPreview } from "./plate-input"
import { PopoverPreview } from "./popover"
import { PostalCodePreview } from "./postal-code"
import { PriceInputPreview } from "./price-input"
import { ProgressPreview } from "./progress"
import { QRCodePreview } from "./qr-code"
import { QuestionnairePreview } from "./questionnaire"
import { RadioGroupPreview } from "./radio-group"
import { ReceiptPrinterPreview } from "./receipt-printer"
import { ResizablePreview } from "./resizable"
import { ResponsiveAlertDialogPreview } from "./responsive-alert-dialog"
import { ResponsiveDialogPreview } from "./responsive-dialog"
import { ResponsiveMenuPreview } from "./responsive-menu"
import { ScrollAreaPreview } from "./scroll-area"
import { SelectPreview } from "./select"
import { SeparatorPreview } from "./separator"
import { SheetPreview } from "./sheet"
import { SidebarPreview } from "./sidebar"
import { SkeletonPreview } from "./skeleton"
import { SliderPreview } from "./slider"
import { SpinnerPreview } from "./spinner"
import { StatusButtonPreview } from "./status-button"
import { SwitchPreview } from "./switch"
import { TablePreview } from "./table"
import { TabsPreview } from "./tabs"
import { TextareaPreview } from "./textarea"
import { TimePickerPreview } from "./time-picker"
import { ToastPreview } from "./toast"
import { ToggleGroupPreview } from "./toggle-group"
import { TogglePreview } from "./toggle"
import { TomanIconPreview } from "./toman-icon"
import { TooltipPreview } from "./tooltip"
import { TypographyPreview } from "./typography"
import { UseControllableStatePreview } from "./use-controllable-state"
import { UseCopyToClipboardPreview } from "./use-copy-to-clipboard"
import { UseCountdownPreview } from "./use-countdown"
import { UseDatePreview } from "./use-date"
import { UseMediaQueryPreview } from "./use-media-query"
import { UseTimeAgoPreview } from "./use-time-ago"
import { WheelPickerPreview } from "./wheel-picker"

export const OG_PREVIEWS: Record<string, ComponentType> = {
  accordion: AccordionPreview,
  "alert-dialog": AlertDialogPreview,
  alert: AlertPreview,
  "aspect-ratio": AspectRatioPreview,
  attachment: AttachmentPreview,
  avatar: AvatarPreview,
  badge: BadgePreview,
  "bank-input": BankInputPreview,
  breadcrumb: BreadcrumbPreview,
  bubble: BubblePreview,
  "button-group": ButtonGroupPreview,
  button: ButtonPreview,
  calendar: CalendarPreview,
  card: CardPreview,
  carousel: CarouselPreview,
  charts: ChartsPreview,
  checkbox: CheckboxPreview,
  "city-selector": CitySelectorPreview,
  collapsible: CollapsiblePreview,
  combobox: ComboboxPreview,
  command: CommandPreview,
  "context-menu": ContextMenuPreview,
  "copy-button": CopyButtonPreview,
  "data-table": DataTablePreview,
  "date-picker": DatePickerPreview,
  "date-wheel-picker": DateWheelPickerPreview,
  dialog: DialogPreview,
  direction: DirectionPreview,
  drawer: DrawerPreview,
  "dropdown-menu": DropdownMenuPreview,
  "elastic-range-slider": ElasticRangeSliderPreview,
  "elastic-slider": ElasticSliderPreview,
  empty: EmptyPreview,
  field: FieldPreview,
  hitbox: HitboxPreview,
  "hover-card": HoverCardPreview,
  "input-group": InputGroupPreview,
  "input-otp": InputOTPPreview,
  input: InputPreview,
  "iranian-bank": IranianBankPreview,
  item: ItemPreview,
  kbd: KbdPreview,
  label: LabelPreview,
  marker: MarkerPreview,
  menubar: MenubarPreview,
  "message-scroller": MessageScrollerPreview,
  message: MessagePreview,
  "mobile-number-input": MobileNumberInputPreview,
  "national-id-input": NationalIDInputPreview,
  "national-id": NationalIdPreview,
  "native-select": NativeSelectPreview,
  "navigation-menu": NavigationMenuPreview,
  "normalize-persian-digits": NormalizePersianDigitsPreview,
  "number-to-persian-words": NumberToPersianWordsPreview,
  pagination: PaginationPreview,
  "password-input": PasswordInputPreview,
  "persian-date-zod": PersianDateZodPreview,
  "persian-date": PersianDatePreview,
  "persian-holidays": PersianHolidaysPreview,
  "persian-reshape": PersianReshapePreview,
  "persian-slug": PersianSlugPreview,
  "plate-input": PlateInputPreview,
  popover: PopoverPreview,
  "postal-code": PostalCodePreview,
  "price-input": PriceInputPreview,
  progress: ProgressPreview,
  "qr-code": QRCodePreview,
  questionnaire: QuestionnairePreview,
  "radio-group": RadioGroupPreview,
  "receipt-printer": ReceiptPrinterPreview,
  resizable: ResizablePreview,
  "responsive-alert-dialog": ResponsiveAlertDialogPreview,
  "responsive-dialog": ResponsiveDialogPreview,
  "responsive-menu": ResponsiveMenuPreview,
  "scroll-area": ScrollAreaPreview,
  select: SelectPreview,
  separator: SeparatorPreview,
  sheet: SheetPreview,
  sidebar: SidebarPreview,
  skeleton: SkeletonPreview,
  slider: SliderPreview,
  spinner: SpinnerPreview,
  "status-button": StatusButtonPreview,
  switch: SwitchPreview,
  table: TablePreview,
  tabs: TabsPreview,
  textarea: TextareaPreview,
  "time-picker": TimePickerPreview,
  toast: ToastPreview,
  "toggle-group": ToggleGroupPreview,
  toggle: TogglePreview,
  "toman-icon": TomanIconPreview,
  tooltip: TooltipPreview,
  typography: TypographyPreview,
  "use-controllable-state": UseControllableStatePreview,
  "use-copy-to-clipboard": UseCopyToClipboardPreview,
  "use-countdown": UseCountdownPreview,
  "use-date": UseDatePreview,
  "use-media-query": UseMediaQueryPreview,
  "use-time-ago": UseTimeAgoPreview,
  "wheel-picker": WheelPickerPreview,
}
