// One-off: extracts oklch theme data from the local shadcn registry clone
// into apps/web/lib/create/theme-data.ts. Run from repo root: bun scripts/extract-themes.mts
import { THEMES } from "../_example/shadcn/apps/v4/registry/themes.ts"

const KEYS = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "border",
  "input",
  "ring",
]
const BASE = ["neutral", "stone", "zinc"]
const ACCENTS = [
  "amber",
  "blue",
  "cyan",
  "emerald",
  "fuchsia",
  "green",
  "indigo",
  "lime",
  "orange",
  "pink",
  "purple",
  "red",
  "rose",
  "sky",
  "teal",
  "violet",
  "yellow",
]

const pick = (t: (typeof THEMES)[number]) => ({
  light: Object.fromEntries(KEYS.map((k) => [k, t.cssVars!.light![k]!])),
  dark: Object.fromEntries(KEYS.map((k) => [k, t.cssVars!.dark![k]!])),
})

const baseColors: Record<string, unknown> = {}
const themes: Record<string, unknown> = {}
for (const t of THEMES) {
  if (BASE.includes(t.name)) baseColors[t.name] = pick(t)
  if (t.name === "neutral") themes.neutral = pick(t)
  if (ACCENTS.includes(t.name)) themes[t.name] = pick(t)
}
// gray has no dedicated shadcn v4 theme — reuse zinc (visually closest).
baseColors.gray = baseColors.zinc

const out = `// Generated by scripts/extract-themes.mts from the shadcn registry theme
// data (oklch values). Keys are css var names without the leading "--".
export const BASE_COLOR_VARS: Record<
  string,
  { light: Record<string, string>; dark: Record<string, string> }
> = ${JSON.stringify(baseColors, null, 2)}

export const THEME_VARS: Record<
  string,
  { light: Record<string, string>; dark: Record<string, string> }
> = ${JSON.stringify(themes, null, 2)}
`

await Bun.write(new URL("../apps/web/lib/create/theme-data.ts", import.meta.url), out)
console.log("bases:", Object.keys(baseColors).join(","), "| themes:", Object.keys(themes).length)
